#!/bin/bash

killall -q sxhkd polybar greenclip touchegg
sxhkd &
# xrandr --output HDMI-1 --mode 1440x900 --scale 1x1
~/.fehbg &
launch_polybar
greenclip daemon &
touchegg &
xsetroot -cursor_name left_ptr &
gnome-keyring-daemon --start --components=pkcs11,secrets,ssh
bspc monitor eDP -d 1 2 3 4 5 8 9 0
# bspc monitor HDMI-A-0 -d 1 2 3 4 5
# bspc monitor eDP -d 6 7 8 9 0
# bspc monitor eDP-1 -d 1 2 3 4 5
# bspc monitor HDMI-1 -d 6 7 8 9 0

bspc config border_width 2
bspc config window_gap 10
bspc config top_padding 26

bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config gapless_monocle false

bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus on
bspc config ignore_ewmh_struts true

bspc rule -a "obsidian" desktop=8
bspc rule -a "com.github.th_ch.youtube_music" desktop=9
bspc rule -a "Slack" desktop=0
bspc rule -a "iwgtk" state=floating

xrdb -merge ~/.Xresources
~/.screenlayout/study.sh
slack
