#!/bin/bash
#
killall -q sxhkd &
killall polybar &
killall picom &
killall greenclip
sxhkd &
greenclip daemon &
bash ~/.scripts/switch-theme.sh &
wal -i $WALLPAPER &
polybar &
picom &
bash ~/.scripts/feh-blur --blur 5 -d &

xsetroot -cursor_name left_ptr &
bspc monitor -d 1 2 3 4 5 

# bspc config border_width 1
bspc config border_width 0
bspc config window_gap 13

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer true

