#!/bin/bash

killall -q sxhkd polybar picom greenclip touchegg
sxhkd &
~/.fehbg &
polybar &
picom &
greenclip daemon &
touchegg &
xsetroot -cursor_name left_ptr 
bspc monitor -d 1 2 3 4 5 0

# bspc config border_width 1
bspc config border_width 1
bspc config window_gap 10

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus on

